### ISSUE TITLE
1.21.1 - Server startup error

### ISSUE THREAD

**Issue by KamiliaBlow** [Team-Abode/verdance#29]
When starting the server, I get this error and the server shuts down

```
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'verdance' at 'com.teamabode.verdance.Verdance'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.5.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/terraformersmc/biolith/api/biome/BiomePlacement
	at com.teamabode.verdance.Verdance.registerBiomePlacements(Verdance.java:266) ~[verdance-1.21.1-1.1.3.jar:?]
	at com.teamabode.verdance.Verdance.onInitialize(Verdance.java:52) ~[verdance-1.21.1-1.1.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.terraformersmc.biolith.api.biome.BiomePlacement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.5.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at com.teamabode.verdance.Verdance.registerBiomePlacements(Verdance.java:266) ~[verdance-1.21.1-1.1.3.jar:?]
	at com.teamabode.verdance.Verdance.onInitialize(Verdance.java:52) ~[verdance-1.21.1-1.1.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
	... 6 more
```

[latest.log](https://github.com/user-attachments/files/17265205/latest.log)

**Comment by KamiliaBlow** [comment]
Mod version 1.1.3

**Comment by KamiliaBlow** [comment]
Sorry, looks like the server was missing Biolith, after adding it, the server started loading. Fabric said he only had a need for Sketch, I think you should add a mandatory requirement to check for Biolith so that the person knows that this library is also missing to start.
